### ISSUE TITLE
raf loops aren't necessary

### ISSUE THREAD

**Issue by drcmda** [tim-soft/react-particles-webgl#2]
A small suggestion for: https://github.com/tim-soft/react-particles-webgl/blob/6f86c70fb5282dc6dc6eb0797be0cc627dd4c4ef/src/ParticleField.js#L135-L137

They will downgrade performance a little bit, because useRender contents are already called in a raf loop. You can simply call update functions in there. Browsers don't take multiple frame ops kindly and unifying these operations gives a little bit more room.

**Comment by tim-soft** [comment]
Ah, that makes total sense, I'l make sure there's a note of it in the docs site when it goes live

Thanks for taking a look!
